package de.weltraumschaf.maconha.ui.view.dashboard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Grid;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DashboardViewDesign extends VerticalLayout {
    protected Label numberOfIndexedFiles;
    protected Label numberOfDuplicteFiles;
    protected Label numberOfFoundKeywords;
    protected Grid<de.weltraumschaf.maconha.backend.model.KeywordAndNumberOfMediaFiles> topTenKeywords;

    public DashboardViewDesign() {
        Design.read(this);
    }
}
