package de.weltraumschaf.maconha.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainViewDesign extends HorizontalLayout {
    protected Label activeViewName;
    protected Button menuButton;
    protected CssLayout menu;
    protected Button dashboard;
    protected Button buckets;
    protected Button mediaFiles;
    protected Button keywords;
    protected Button scans;
    protected Button duplicates;
    protected Button logout;
    protected VerticalLayout content;

    public MainViewDesign() {
        Design.read(this);
    }
}
